version: '3.1'
services:
  demo_zookeeper:
    build: ./demo_zookeeper
    ports:
      - "2181:2181"

  demo_kafka:
    build: ./demo_kafka
    ports:
      - "9092:9092"
    restart: always
    depends_on:
      - demo_zookeeper
    links:
      - demo_zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: demo_zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "demo1:1:1,demo2:2:1,demo3:4:1"